### ISSUE TITLE
Ubuntu 16.04 issue

### ISSUE THREAD

**Issue by sildeag** [edzer/spacetime#24]
* installing *source* package ‘spacetime’ ...
** R
** data
** demo
** inst
** tests
** preparing package for lazy loading
in method for ‘coerce’ with signature ‘"RasterStackBrick","STFDF"’: no definition for class “RasterStackBrick”
in method for ‘coerce’ with signature ‘"STFDF","RasterBrick"’: no definition for class “RasterBrick”
in method for ‘stplot’ with signature ‘"RasterStackBrick"’: no definition for class “RasterStackBrick”

What am I missing?

**Comment by edzer** [comment]
You can safely ignore these messages.
