### ISSUE TITLE
 length(object@sp) * nrow(object@time) is not TRUE

### ISSUE THREAD

**Issue by antaldaniel** [edzer/spacetime#27]
I have found this question on Stackoverflow as well [here] (https://stackoverflow.com/questions/37729146/load-spatio-temporal-dataset-with-r-spacetime) 
and elsewhere [here](http://grokbase.com/p/r/r-sig-geo/138tfw4fkc/error-with-stfdf) 
> Error: nrow(object@data) == length(object@sp) * nrow(object@time) is not TRUE

To give a reproducible example, I am creating a random-values dataset for all countries included in the shapefile of Eurostat.  The file is ordered by time (and country.) There are no missing values, and each space-time pair has exactly one row. 

```
EU_NUTS <- rgdal::readOGR(dsn = "./Shapefiles/NUTS_2013_60M_SH/NUTS_2013_60M_SH/data", layer = "NUTS_RG_60M_2013")
EU_NUTS1 <- EU_NUTS[ which (EU_NUTS@data$STAT_LEVL_ == 0 ), ] # subsetting to include only countries
geo_locations <- unique(as.character(EU_NUTS1$NUTS_ID))  

appended <- FALSE
for (i in 2000:2003) {
  for (j in 1:length(geo_locations)) {
      tmp <- data.frame (
      country = geo_locations[j],
      date = as.POSIXct(paste0(i, "-01-01", tz = "GMT")),
      value1 = rnorm(1, mean=50, sd=10),
      value2 = rnorm(1, mean=50, sd=10)
    )
    
    if (!appended) {
      europe <- tmp
      appended <- TRUE
    } else {
      europe <- rbind (europe, tmp)
    }
  } #end of loop j in countries
} # end of loop i in time

issues.st <- STFDF (sp = EU_NUTS1, 
                    time = europe$date, 
                    data = euro[,3:4]) 
```
The error message pops up above even though 
```
length(unique (as.character(EU_NUTS1$NUTS_ID)))*length(unique (europe$date)) == nrow (europe)
```
equals TRUE. 

Even if I am doing something wrong, I am not the only one confused by the error message.

**Comment by edzer** [comment]
The thing goes wrong when the `NUTS_ID` values or the `date` values are not unique. Is this the case? The data provided to function `STFDF` should have `nrows` equal to `length(EU_NUTS1)*length(europe$date)`. As the error message (kind of) says.

**Comment by antaldaniel** [comment]
as.character (EU_NUTS1$NUTS_ID)
 [1] "AT" "BG" "CY" "CZ" "CH" "BE" "DE" "DK" "EE" "EL" "ES" "HR" "HU" "FI" "FR" "IE"
[17] "LI" "LT" "LU" "LV" "ME" "MK" "MT" "NL" "IS" "IT" "PT" "RO" "NO" "PL" "SE" "SK"
[33] "TR" "UK" "SI"

These are the unique country codes of European country. The dates are created by the loop, each country-date pair is unique.

**Comment by edzer** [comment]
Yes, but your date values are not unique. Try passing `time = unique(europe$date)` to `STFDF`. Even then, I have no clue what is in `eurobarometer`.

**Comment by antaldaniel** [comment]
Apologies, that was from my code from which I made the example.  And thank you, that was indeed one of the problems. I think it would be useful to change the documentation that not only space-time pairs have to be unique, but you have to uniquely enumerate them.   I encountered another bad error message. If the unique time vector does not exist, it gives an error

> Error in ST(sp, time, endTime) : time is not a time based class

Probably it would be better to say: time is not based on a time based class or variable does not exist
