### ISSUE TITLE
Package slot missing

### ISSUE THREAD

**Issue by pascaloettli** [edzer/spacetime#29]
An error occurs while loading `spacetime` package, if packages `semiArtificial` and `sirad` are already loaded:

    libs <- c("semiArtificial", "sirad", "spacetime")
    lapply(libs, library, character.only = TRUE)
> Error: package or namespace load failed for ‘spacetime’:
>  package slot missing from signature for generic ‘coerce’
> and classes STFDF, RasterBrick
> cannot use with duplicate class names (the package may need to be re-installed)

Reinstalling the package doesn't solve the problem.

    sessionInfo()
    R version 3.4.1 (2017-06-30)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 16.04.2 LTS

    Matrix products: default
    BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.18.so

    locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
     [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
     [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
     [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] sirad_2.3-3          semiArtificial_2.2.5 sos_2.0-0           
    [4] brew_1.0-6          

    loaded via a namespace (and not attached):
     [1] multicool_0.1-10    zoo_1.8-0           modeltools_0.2-21  
     [4] StatMatch_1.2.5     ks_1.10.7           lpSolve_5.6.13     
     [7] kernlab_0.9-25      splines_3.4.1       lattice_0.20-35    
    [10] flexclust_1.3-4     htmltools_0.3.6     stats4_3.4.1       
    [13] survival_2.41-3     prabclus_2.2-6      sp_1.2-5           
    [16] fpc_2.1-10          robustbase_0.92-7   timeDate_3012.100  
    [19] raster_2.5-8        ncdf4.helpers_0.3-3 htmlwidgets_0.9    
    [22] mvtnorm_1.0-6       codetools_0.2-15    misc3d_0.8-4       
    [25] knitr_1.16          httpuv_1.3.5        flexmix_2.3-14     
    [28] parallel_3.4.1      class_7.3-14        DEoptimR_1.0-8     
    [31] xts_0.10-0          trimcluster_0.1-2   Rcpp_0.12.12       
    [34] KernSmooth_2.23-15  xtable_1.8-2        diptest_0.75-7     
    [37] CORElearn_1.50.3    jsonlite_1.5        PCICt_0.5-4        
    [40] FNN_1.1             mime_0.5            RANN_2.5.1         
    [43] digest_0.6.12       mcclust_1.0         shiny_1.0.3        
    [46] ncdf4_1.16          logspline_2.1.9     survey_3.32-1      
    [49] grid_3.4.1          clue_0.3-53         tools_3.4.1        
    [52] magrittr_1.5        rgl_0.98.1          proxy_0.4-17       
    [55] cluster_2.0.6       MASS_7.3-47         RSNNS_0.4-9        
    [58] Matrix_1.2-10       R6_2.2.2            mclust_5.3         
    [61] rpart_4.1-11        intervals_0.15.1    nnet_7.3-12        
    [64] compiler_3.4.1

**Comment by edzer** [comment]
```r
> library("spacetime")
> library("sirad")
> library("semiArtificial")
```
seems to work.

**Comment by pascaloettli** [comment]
Yes, but the order shouldn't matter.

**Comment by edzer** [comment]
Then please point out why when it does, this is an issue of `spacetime` and not of the other packages.

**Comment by BenGraeler** [comment]
I face a similar issue checking an R package that uses both raster and spacetime. Inspired by [this thread](https://stat.ethz.ch/pipermail/r-devel/2012-August/064574.html), I checked `str(getMethod("coerce", c("STFDF", "RasterBrick")))` and saw that the slot "package" contained either `c("", "raster")` or `c("spacetime", "")` depending on which package has been loaded first. Encapsulating the definition of `setAs` for `STFDF` and `RasterBrick` in spacetime with `if ( require("raster", quietly = TRUE)) { ... }` lets my package pass R check and the package slot now reads `c("spacetime", "raster")`. Not sure if this is an entirely valid solution, but it might shed some light on the issue.

**Comment by edzer** [comment]
Does that still give a clean check on `spacetime`?

**Comment by BenGraeler** [comment]
Well, the test/raster.R is an issue. Installing the package locally and running the test works fine as raster is installed. However, in the check environment, raster is absent, as it is only a suggested package. Hence, the test fails, as the coerce and stplot methods are not defined when installing the package in a clean check environment.

**Comment by edzer** [comment]
Which check environment?

**Comment by BenGraeler** [comment]
When checking the package, ```require("raster", quietly = TRUE)``` evaluates to ```FALSE``` and the coerce functions are not present. This is different when the package is installed where the above evaluates to ```TRUE``` and the coerce functions are present. In the case where "raster" is listed in the "Imports" field and not in the "Suggests" field, the above evaluates to ```TRUE``` when installing and checking the package.

**Comment by edzer** [comment]
So, moving `raster` to `Imports:` would solve the problem?

**Comment by BenGraeler** [comment]
With ```raster``` in ```Imports:```, the test ```tests/raster.R``` succeeds again. In summary, there are two changes:

1. Explicitly loading ```raster``` before the coerce functions are defined in ```spacetime``` (inserting ```requireNamespace("raster", quietly = TRUE)``` in ```R/raster.R```)
2. moving ```raster``` into ```Imports:```

My latest commit also tests in ```tests/raster.R``` for empty package slots and whether ```stplot``` has a method for ```RasterStackBrick```.

**Comment by edzer** [comment]
I don't see why (and where) 1. is needed when we would do 2. AFAICT you are supposed to used `requireNamespace` inside functions, not at top level.

**Comment by BenGraeler** [comment]
Suggestion: if ```spacetime``` and ```raster``` both only coerce to their classes, the error can be avoided as no duplicated ```as-methods``` (with mismatching package slots) are present. 

On the issue:
I played around with the issue, but I do not have a clue why it makes a difference here whether ```raster``` is merely imported and the additional use of ```requireNamespace```: 

1. When installing ```spaetime``` without the use of ```requireNamespace```, I see messages during install like ```in method for ‘coerce’ with signature ‘"RasterStackBrick","STFDF"’: no definition for class “RasterStackBrick”``` and after loading spacetime, ```str(getMethod("coerce", c("STFDF", "RasterBrick")))``` has one empty package slot. 

2. With using ```requireNamespace``` I neither see the message during install, nor does the coerce function has an empty package slot. 

Nevertheless, the ```as-methods``` work as expected either way within ```spacetime``` (as in the current state with ```raster``` in ```Suggests:```). However, using ```spacetime``` and ```raster``` in another package, I get: 
```Error: package slot missing from signature for generic ‘coerce’
   and classes STFDF, RasterBrick
   cannot use with duplicate class names (the package may need to be re-installed)``` during the package check. With changes in ```raster``` and ```spacetime``` (i.e. preceding the coerce definitions by ```requireNamespace```), the check succeeds.

The use of ```requireNamespace``` was based on "You never need to use require() (requireNamespace() is almost always better)" from http://r-pkgs.had.co.nz/namespace.html.

**Comment by edzer** [comment]
When you import, you add both to DESCRIPTION and NAMESPACE, right? In that case, the namespace should have been imported.

**Comment by BenGraeler** [comment]
It is, sorry for the noise. I embarrassingly added it only to the DESCRIPTION. 

Is there any reason why ```spacetime``` and ```raster``` both provide an as-method to coerce from ```STFDF``` to ```RasterBrick```? Wouldn't it make sense to provide coerce functions only for "imports"?

**Comment by edzer** [comment]
I dont' know, but `getMethod("coerce", c("STFDF", "RasterBrick"))` when taken from `raster`'s namespace doesn't look good to me.
