### ISSUE TITLE
how to explain the results fot the EOF analysis?

### ISSUE THREAD

**Issue by xiyanzhong** [edzer/spacetime#31]
![image](https://user-images.githubusercontent.com/34880590/34938893-d5aea1ea-fa24-11e7-8561-88d44827385d.png)
HI,
I've been reading some reference to conduct EOF's, and have tried to conduct ,but I have a little understanding of the results :
1) the results inculde the parameters "sdev"     "rotation" "center"   "scale"    "x"        "call" , What does that mean for the rotation and X parameters ?
Thanks,

**Comment by edzer** [comment]
You may want to read up on the documentation of `?prcomp`.
