### ISSUE TITLE
how to realize the spatio-temporal cokriging with variogramST function

### ISSUE THREAD

**Issue by gig210** [edzer/spacetime#42]
Hi, I am working on the spatiotemporal interplation of air temperature. I want to realize the work using the spatiotemporal cokriging, but I have found the code of spatiotemporal kriging. How to realize the spatio-temporal cokriging with variogramST function from the spatiotemporal kriging?? Thanks.

**Comment by edzer** [comment]
I don't think you can do that with gstat.

**Comment by edzer** [comment]
(closing here: not an issue of this package)
